"""initial

Revision ID: 5b91888a525f
Revises: 
Create Date: 2026-05-07 14:35:41.279827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b91888a525f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('arena', sa.String(length=100), nullable=False),
    sa.Column('rua', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('atleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('residente_eldorado', sa.Boolean(), nullable=False),
    sa.Column('nivel_validado', sa.Boolean(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(length=20), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convite_parceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_origem_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nome_parceiro', sa.String(length=100), nullable=False),
    sa.Column('telefone_parceiro', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['atleta_origem_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta1_id', sa.Integer(), nullable=False),
    sa.Column('atleta2_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['atleta1_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['atleta2_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('inscricao')
    op.drop_table('convite_parceiro')
    op.drop_table('categoria')
    op.drop_table('atleta')
    op.drop_table('nivel')
    op.drop_table('evento')
    # ### end Alembic commands ###
